spring.application.name=FINEXP
server.port=8081
logging.config=classpath:logback-spring.xml

# DB connection
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/fin_exp
spring.datasource.username=postgres
spring.datasource.password=postgres
#  postgres
#  T7p!zX9q@Lm2
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.flyway.enabled=false
application.locales=en_us
usermessage.resourceBundles=framework

# Security
#security.jwt.secret-key="xcOt1/3a4nh9O/Vy6e6w2bU4vAUqN9ZzphM2TtdU3DLNnlrWdRFany4f3V5BkbA2Cbq7C8DeYmyn0g8ryoNvcg=="
#security.jwt.secret-key=OPM8bpXJyVHR9adpwgoEpQnY7LKC8Oz0FDbdRZ6E3qY=
security.jwt.secret-key=OPM8bpXJyVHR9adpwgoEpQnY7LKC8Oz0FDbdRZ6E3qY=
security.jwt.expiration-time=86400000
security.jwt.refresh-expiration-time=604800000
#spring.jpa.open-in-view=false
# Admin
admin.email=admin@finexp.com
admin.phone=+250780905792
admin.firstname=Mugisha
admin.lastname=Blaise
admin.password=Open123..
admin.role=ADMIN

